title: Polywit
description: A poly-language execution-based violation-witness validator
favicon: true
plugins:
  - jekyll-remote-theme
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
logo: /assets/logo-small.png

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/polywit/polywit
